# Generated by Django 4.1.2 on 2022-12-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='flights/static/profile_pics'),
        ),
    ]
