# Generated by Django 4.1.2 on 2023-01-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_airport_city_alter_profile_image_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='city_airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='flights.city'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='departure_airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='destination_airport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='flights.airport'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flights.city'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destination_city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='flights.city'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
